- hosts: all
  tasks:

  - name: "configer file"
    copy:
      src: "/root/ansible/haproxy.cfg"
      dest: "/etc/haproxy/"
  - name: "start service"
    service: 
      name: "haproxy"
      state: started

      
      
  
