- hosts: all
  tasks:
  - name: "Install httpd"
    package:
      name: "httpd"
      state: present
  - name: "Copy Containt "
    copy:
      dest: "/var/www/html/auth.html"
      content: "helllo"
  - name: "Replace"
    replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride Authconfig"     
  - name: "Copy htaccess"
    copy:
      dest: "/var/www/html/.htaccess"
      src: "/var/www/html/.htaccess"      
  - name: "Install python36"
    package:
      name: "python36"
      state: present      
  - name: "pip install passlib"
    pip:
      name: "passlib"      
  - name: "htpasswd"
    htpasswd:
      name: "sagar"
      password: "sws"
      path: "/etc/www.passwd" 
  - name: "service start"
    service:
      name: "httpd"
      state: restarted
 
 
 
 
