- hosts: all
  tasks:
  - name: "install httpd"
    package:
      name: "httpd"
      state: present
  - name: "Copy Containt "
    copy:
      dest: "/var/www/html/auth.html"
      content: "helllo"
      
      
      
      
      
