- hosts: all
  tasks:
  - name: "install httpd"
    package:
      name: "httpd"
      state: present
  - name: "Copy Containt "
    copy:
      dest: "/var/www/html/auth.html"
      content: "helllo"
  - name: "replace"
    replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride Authconfig"     
  - name: "copy htaccess"
    copy:
      dest: "/var/www/html/.htaccess"
      src: "/var/www/html/.htaccess"      
      
      
      
